name: Create Release and publish packages

on:
  push:
    tags:
    # Tags in the form: es-ES-vmajor.minor.patch
    # e.g. zh-CN@v0.0.1
    - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade -r requirements/release.txt
    - name: Prepare env variables
      run: |
        echo "CURRENT_TAG=$(python .github/scripts/parse_ref.py)" >> $GITHUB_ENV
        echo "CURRENT_LOCALE_DIR=$(python .github/scripts/parse_release.py)" >> $GITHUB_ENV
    - name: Build release artefacts
      run: |
        cd ${{ env.CURRENT_LOCALE_DIR }}
        check-manifest -v
        python setup.py sdist bdist_wheel
        python -m twine check dist/*
        ls
    - name: Create Release
      run: |
        hub release create \
        ${{ env.CURRENT_TAG }} \
        -m Release ${{ env.CURRENT_TAG }} \
        -m Release ${{ env.CURRENT_TAG }} \
        -a ${{ env.CURRENT_LOCALE_DIR }}/dist/* 
      env:
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish PyPI Package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        cd ${{ env.CURRENT_LOCALE_DIR }}
        python -m twine upload dist/*
        ls
